# Generated by Django 5.2 on 2025-04-23 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeLog',
            new_name='UserTimeLog',
        ),
    ]
