# Generated by Django 5.2 on 2025-04-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_staff_timelog_delete_usertimelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='staff_username',
        ),
    ]
