# Generated by Django 5.2 on 2025-04-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_staff_id_staff_staff_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_password',
            field=models.CharField(default='defaultpassword', max_length=100),
        ),
    ]
