# Generated by Django 5.2 on 2025-04-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staff_staff_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_password',
        ),
    ]
