# Generated by Django 5.2.1 on 2025-05-13 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
    ]
